spring.application.name=cadastroCarrosAlugados
spring.datasource.url=jdbc:postgresql://localhost:5432/carros
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jba.hibernate.ddl-auto=update
spring.jba.show-sql=true
spring.jba.properties.hibernate.format_sql=true